[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "amount = amount or 1"
position = "at"
payload = '''
    amount = amount or 1
    hasopenwater = false
    print('test')
    for i, v in ipairs(G.jokers.cards) do
        if G.jokers.cards[i].ability.name == 'j_joey_openwater' then
            hasopenwater = true
            print(hasopenwater)
        end
    end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)"
position = "at"
payload = '''
if hasopenwater == false then 
    G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
else
    for i, v in ipairs(G.jokers.cards) do
        if G.jokers.cards[i].ability.name == 'j_joey_openwater' then
            for h, k in pairs(G.GAME.hands) do 
                v.ability.extra.savedchips[h] = math.max(v.ability.extra.savedchips[h] + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
                G.GAME.hands[h].chips = 1
            end
        end
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "update_hand_text({delay = 0}, {chips = G.GAME.hands[hand].chips, StatusText = true})"
position = "at"
payload = '''
if hasopenwater == false then
    update_hand_text({delay = 0}, {chips = G.GAME.hands[hand].chips, StatusText = true})
end
'''
match_indent = true
times = 1
