[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "amount = amount or 1"
position = "at"
payload = '''
    amount = amount or 1
    hasopenwater = false
    print('test')
    for i, v in ipairs(G.jokers.cards) do
        if G.jokers.cards[i].ability.name == 'j_joey_openwater' then
            hasopenwater = true
            print(hasopenwater)
        end
    end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)"
position = "at"
payload = '''
if hasopenwater == false then 
    G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
else
    for i, v in ipairs(G.jokers.cards) do
        if G.jokers.cards[i].ability.name == 'j_joey_openwater' then
            for h, k in pairs(G.GAME.hands) do 
                v.ability.extra.savedchips[h] = math.max(v.ability.extra.savedchips[h] + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
                G.GAME.hands[h].chips = 1
            end
        end
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "update_hand_text({delay = 0}, {chips = G.GAME.hands[hand].chips, StatusText = true})"
position = "at"
payload = '''
if hasopenwater == false then
    update_hand_text({delay = 0}, {chips = G.GAME.hands[hand].chips, StatusText = true})
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
G.FUNCS.can_start_run = function(e)
    if not G.GAME.viewed_back.effect.center.unlocked then 
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
    else
        e.config.colour = G.C.BLUE
        e.config.button = 'start_setup_run'
    end
  end
'''
position = "at"
payload = '''
G.FUNCS.can_start_run = function(e)
    local selectable = true
    if not G.GAME.viewed_back.effect.center.unlocked then 
        selectable = false
    elseif G.GAME.viewed_back.name == 'b_joey_honkifex' then
        if G.PROFILES[G.SETTINGS.profile].successorTokens <= 0 then
            selectable = false
        end
    end
    if selectable then
        e.config.colour = G.C.BLUE
        e.config.button = 'start_setup_run'
    else
        e.config.colour = G.C.UI.BACKGROUND_INACTIVE
        e.config.button = nil
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = 'if key == "r" and not G.SETTINGS.paused then'
position = "after"
payload = '''
if G.GAME.selected_back.name == 'b_joey_honkifex' and G.PROFILES[G.SETTINGS.profile].successorTokens <= 0 then return end
'''
match_indent = true
times = 1